behaviors:
  Auv:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512
      buffer_size: 10240
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 1e6
    time_horizon: 128
    summary_freq: 12000
    threaded: True
# env_settings:
#   env_path: "build\\"
#   env_args: null
#   base_port: 5005
#   num_envs: 4
#   num_areas: 1
#   seed: -1
#   max_lifetime_restarts: 10
#   restarts_rate_limit_n: 1
#   restarts_rate_limit_period_s: 60
